server:
  port: 8080
spring:
  application:
    name: payment-clean
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 50MB
pcacVersion: V1.3.0