logging:
  config: classpath:log4j2-dev.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zfqs
    password: Zaq!@#123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.48.224/zfqs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai

server:
  port: 8081

pcac:
  url: https://localhost:8081/pcac
  version: V1.3.0
  orig-sender: Z2004343000017
  orig-sender-sid: zf_sysstem
  login-url: http://210.12.239.161:10001/ries_interface/loginServlet
  business-url: http://210.12.239.161:10001/ries_interface/httpServlet
  user-token: Io2lrHofKybUc%2BmKeG6qo%2FMQwXMQTOQ6IwrnIfgvhyHTf2SAN63W0wKbw%2FODal5I

sftp:
  host: 172.16.48.89
  port: 22
  username: zfqs
  password: Root@123
  modDir: /tmp/
  remotePathUpload: /ftp_data/zfqs/input/
  remotePathDownload: /ftp_data/zfqs/output/
  queryPcacMerchantRiskInfoFileNamePrefix: Risk_
  pcacRiskInfoFileNamePrefix: Black_
  businessInfoFileNamePrefix: Business_
