logging:
  config: classpath:log4j2-dev.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zfqs
    password: Zaq!@#123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.48.224/zfqs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai

server:
  port: 8081

pcac:
  url: https://localhost:8081/pcac
  version: V1.3.0
  orig-sender: pcac10086
  orig-sender-sid: pcac10086

sftp.host: 172.16.48.89
sftp.port: 22
sftp.username: zfqs
sftp.password: Root@123
sftp.modDir: /tmp/
sftp.remotePathUpload: /ftp_data/zfqs/input/
sftp.remotePathDownload: /ftp_data/zfqs/output/
sftp.queryPcacMerchantRiskInfoFileNamePrefix: Risk_
sftp.pcacRiskInfoFileNamePrefix: Black_
sftp.businessInfoFileNamePrefix: Business_
