logging:
  config: classpath:log4j2-dev.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/paymentclean?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

server:
  port: 8081